name: Build

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Actualizado a la versión 4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential gcovr  # Agregado gcovr para informes de cobertura

      - name: Configure, Build, and Test
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON  # Habilita la cobertura
          cmake --build .
          ctest --output-on-failure
          # Genera informe de cobertura (ejemplo para gcovr)
          gcovr --exclude-throw-branches --xml-pretty --output coverage.xml

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: build/coverage.xml

  sonar_analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: tests  # Depende del job "tests" para ejecutarse después
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Coverage Report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: build/

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_COVERAGE_REPORT_PATHS: build/coverage.xml  # Ruta del informe de cobertura